version: '2'

volumes:
  database_data:
    driver: local

services:
  php-fpm:
    build: ./docker/php-fpm/
    working_dir: /var/www/
    expose:
      - 9000
    links:
      - mysql
    volumes:
      - .:/var/www

  php-cli:
    build: ./docker/php-cli/
    working_dir: /var/www/
    ports:
      - 9090:9090
    links:
      - mysql
    volumes_from:
      - php-fpm

  apache2:
    build: ./docker/apache/
    working_dir: /var/www/
    environment:
      - APP_DOMAIN=local.alexagile.com
      - APP_DOC_ROOT=/var/www/web
      - APACHE_SERVERNAME=AlexAgile
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_PID_FILE=/var/run/apache2/apache2.pid
      - APACHE_RUN_DIR=/var/run/apache2
      - APACHE_LOCK_DIR=/var/lock/apache2
      - APACHE_LOG_DIR=/var/log/apache2
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm
    volumes_from:
      - php-fpm
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: alexagile
      MYSQL_DATABASE: alexagile
      MYSQL_USER: alexagile
      MYSQL_PASSWORD: alexagile
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - database_data:/var/lib/mysql

  # container usage:
  #  docker run --rm -v $(pwd):/var/www -v ~/.ssh:/root/.ssh -w /var/www composer:latest [command]
  composer:
    image: composer:latest
    working_dir: /var/www/
    volumes_from:
      - php-fpm
    command: install
